# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc08195ccba006f8eaf062c0c346e3609b986b2b52bbac9f61c2be26579c8147133a46c6c7a99bdf4556196503da7bd38557a4c83f0483626ddc600b6acd086

test:
  secret_key_base: 4c05f75cdf34a0c8a75a64a752c4135505bf2b11ea199f3a401ad452b711148a92171619236f259a69adb685eb5563f85553386fdcc15829c3ddaf9cdde5297e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
